export enum ActionType {
 

  // ASSESSMENT APP
  START_ASSESSMENT = "START_ASSESSMENT",
  END_ASSESSMENT = "END_ASSESSMENT",
  GET_QUESTION = "GET_QUESTION",
  UPDATE_ANSWER = "UPDATE_ANSWER",
  LOAD_QUESTION = "LOAD_QUESTION",
  SUBMIT_ANSWER = "SUBMIT_ANSWER",
  UPDATE_QUESTION_STATUS = "UPDATE_QUESTION_STATUS",
  START_QUESTION_LOADING = "START_QUESTION_LOADING",
  END_QUESTION_LOADING = "END_QUESTION_LOADING",
  SHOW_REVIEW = "SHOW_REVIEW",
  HIDE_REVIEW = "HIDE_REVIEW",
  SET_COMPLETED = "SET_COMPLETED",
  ANSWER_SKIPPING = "ANSWER_SKIPPING",
  LOAD_QUESTION_BY_INDEX = "LOAD_QUESTION_BY_INDEX",
  UPDATE_TIME_ELAPSED = "UPDATE_TIME_ELAPSED",

  OPEN_ASSESSMENT_DRAWER = "OPEN_ASSESSMENT_DRAWER",
  CLOSE_ASSESSMENT_DRAWER = "CLOSE_ASSESSMENT_DRAWER",

}
